// @generated by telorgon-shader-build; do not edit.

pub(crate) const BUNDLE_INTERFACE_MAJOR: u32 = 2;
pub(crate) const BUNDLE_INTERFACE_MINOR: u32 = 0;
pub(crate) const BUNDLE_HASH: &str =
    "e29fa0a0edaf5942afadbc918c787d2dd02c00d25aa06691f9a4aa03dda41fa6";
pub(crate) const BOX_VERTEX_HASH: &str =
    "3bdd3491bf549d4bb6c8b248ead08befd8099078f5ecf1641ae2b8def3f141df";
pub(crate) const BOX_VERTEX: &[u8] = include_bytes!("shaders/vulkan/box.vert.spv");
pub(crate) const BOX_FRAGMENT_HASH: &str =
    "b730bc9ae067b3c29aafd5dd05791446f10daacf7b3440f141ccf5fdd4da0bf9";
pub(crate) const BOX_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/box.frag.spv");
pub(crate) const GLYPH_VERTEX_HASH: &str =
    "999e530eeafadc9465abbd15523c15177a97d01a25f5c9c823567bafa6380656";
pub(crate) const GLYPH_VERTEX: &[u8] = include_bytes!("shaders/vulkan/glyph.vert.spv");
pub(crate) const GLYPH_FRAGMENT_HASH: &str =
    "2845d8acce83c5a70f3291f1d9237a545d268b94dcf4b2cf5f8b5235c05292b7";
pub(crate) const GLYPH_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/glyph.frag.spv");
pub(crate) const IMAGE_VERTEX_HASH: &str =
    "0b02a16d34e2e2a6cf3973a6665748315154eb16107ecaffc43814629964f47b";
pub(crate) const IMAGE_VERTEX: &[u8] = include_bytes!("shaders/vulkan/image.vert.spv");
pub(crate) const IMAGE_FRAGMENT_HASH: &str =
    "7426627d70955d8e8272ebfa312a5d58a2ea7278eb09cb40fa58c3131b2f11c8";
pub(crate) const IMAGE_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/image.frag.spv");
pub(crate) const MATERIAL_VERTEX_HASH: &str =
    "3bca7cb419fe89471c49558500be274fcb4a21d9f76993ee1d7521bdb2e5b307";
pub(crate) const MATERIAL_VERTEX: &[u8] = include_bytes!("shaders/vulkan/material.vert.spv");
pub(crate) const MATERIAL_FRAGMENT_HASH: &str =
    "dbafa9f3adc0e5e030a9e0fe932d32340258e0568f40dcb56cbe4a928db08693";
pub(crate) const MATERIAL_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/material.frag.spv");
