// @generated by telorgon-shader-build; do not edit.

pub(crate) const BUNDLE_INTERFACE_MAJOR: u32 = 4;
pub(crate) const BUNDLE_INTERFACE_MINOR: u32 = 0;
pub(crate) const BUNDLE_HASH: &str =
    "ef42107c4738f36021bf064213e6582baf2e71adbca7a9994a32bce29d0a7bb0";
pub(crate) const BOX_VERTEX_HASH: &str =
    "74a5ca1a74dade29acd48781047899fd7ae626e32c39ccd49862134b011ecbfe";
pub(crate) const BOX_VERTEX: &[u8] = include_bytes!("shaders/vulkan/box.vert.spv");
pub(crate) const BOX_FRAGMENT_HASH: &str =
    "b2c50fe41d2b42c412754cfe6ca1321ae3bbd186c9868fc1771e4fb942d06369";
pub(crate) const BOX_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/box.frag.spv");
pub(crate) const GLYPH_VERTEX_HASH: &str =
    "deaec55e693a5a735813197cee82c05b283f84587b7131d57def08919ec4331a";
pub(crate) const GLYPH_VERTEX: &[u8] = include_bytes!("shaders/vulkan/glyph.vert.spv");
pub(crate) const GLYPH_FRAGMENT_HASH: &str =
    "9b4643de4e9c059bec5b2e549a3ae79883a48fb9443bd4138e1a337b1d32ae94";
pub(crate) const GLYPH_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/glyph.frag.spv");
pub(crate) const IMAGE_VERTEX_HASH: &str =
    "0e78d740032e2754466bc6750bdca100dde5fbd0411e2a98b6bea5e9852babb3";
pub(crate) const IMAGE_VERTEX: &[u8] = include_bytes!("shaders/vulkan/image.vert.spv");
pub(crate) const IMAGE_FRAGMENT_HASH: &str =
    "b442394e14f70d0a400c3c40451382f918795900b5cbb5c670a926ee39d607ec";
pub(crate) const IMAGE_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/image.frag.spv");
pub(crate) const MATERIAL_VERTEX_HASH: &str =
    "783af7da04c758dc2db03d1187818f7a77548101504d07d1f29a8314a806fe3c";
pub(crate) const MATERIAL_VERTEX: &[u8] = include_bytes!("shaders/vulkan/material.vert.spv");
pub(crate) const MATERIAL_FRAGMENT_HASH: &str =
    "ec64b3c4ccd3a9079df63cc80f48a1fac026b853d9f8cfe2f9c7edf9a5fcf9a6";
pub(crate) const MATERIAL_FRAGMENT: &[u8] = include_bytes!("shaders/vulkan/material.frag.spv");
