use std::fmt::Write as _;
use std::path::Path;

use crate::manifest::GeneratedBundle;

pub fn source(bundle: &GeneratedBundle, artifact_dir: &Path) -> String {
    let mut output = String::from("// @generated by telorgon-shader-build; do not edit.\n\n");
    writeln!(
        output,
        "pub(crate) const BUNDLE_INTERFACE_MAJOR: u32 = {};",
        bundle.interface_major
    )
    .unwrap();
    writeln!(
        output,
        "pub(crate) const BUNDLE_INTERFACE_MINOR: u32 = {};",
        bundle.interface_minor
    )
    .unwrap();
    writeln!(
        output,
        "pub(crate) const BUNDLE_HASH: &str =\n    {:?};",
        bundle.bundle_hash
    )
    .unwrap();
    for shader in &bundle.shader {
        let constant = shader.name.to_ascii_uppercase();
        let path = artifact_dir
            .join(&shader.artifact)
            .to_string_lossy()
            .replace('\\', "/");
        writeln!(
            output,
            "pub(crate) const {constant}_HASH: &str =\n    {:?};",
            shader.artifact_hash
        )
        .unwrap();
        writeln!(
            output,
            "pub(crate) const {constant}: &[u8] = include_bytes!({path:?});"
        )
        .unwrap();
    }
    output
}
