use std::any::{Any, TypeId};

use crate::compose::{
    Element, InputsChangedContext, MountContext, RuntimeTarget, Signal, SignalDependency,
    SignalSnapshot, UnmountContext, View, ViewError,
};

/// Stable generational identity assigned to one persistent component instance.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ComponentInstanceId {
    index: u32,
    generation: u32,
}

impl ComponentInstanceId {
    #[doc(hidden)]
    pub const fn new(index: u32, generation: u32) -> Self {
        Self { index, generation }
    }

    pub const fn index(self) -> u32 {
        self.index
    }

    pub const fn generation(self) -> u32 {
        self.generation
    }
}

/// Persistent Rust component contract. The component object owns its local state.
pub trait Component: ComponentFields + Sized + 'static {
    fn view(&self) -> impl View;

    fn watch<T>(&self, signal: &Signal<T>) -> SignalSnapshot<T>
    where
        T: Send + Sync + 'static,
    {
        crate::compose::context::watch::<Self, T>(signal)
    }

    fn runtime_target(&self) -> RuntimeTarget {
        crate::compose::context::target::<Self>()
    }

    fn component_instance(&self) -> ComponentInstanceId {
        crate::compose::context::owner::<Self>()
    }

    fn mounted(&mut self, _cx: &mut MountContext<Self>) {}

    fn inputs_changed(&mut self, _cx: &mut InputsChangedContext<Self>) {}

    fn unmounted(&mut self, _cx: &mut UnmountContext<Self>) {}
}

/// Plumbing generated by `#[component]` from the `#[input]` and `#[state]` field declarations.
#[doc(hidden)]
pub trait ComponentFields: Sized + 'static {
    type InputSnapshot: 'static;

    fn update_inputs(&mut self, incoming: Self) -> bool;
    fn capture_inputs(&self) -> Self::InputSnapshot;
    fn restore_inputs(&mut self, snapshot: Self::InputSnapshot) -> bool;
}

/// Runtime-facing erased component instance.
#[doc(hidden)]
pub trait ErasedComponent: Any {
    fn component_type_id(&self) -> TypeId;
    fn component_type_name(&self) -> &'static str;
    fn as_any_mut(&mut self) -> &mut dyn Any;
    fn into_any(self: Box<Self>) -> Box<dyn Any>;
    fn update_from(&mut self, incoming: Box<dyn ErasedComponent>) -> Result<bool, ViewError>;
    fn render(&self, owner: ComponentInstanceId, target: RuntimeTarget) -> RenderedView;
    fn mounted_erased(&mut self, owner: ComponentInstanceId) -> bool;
    fn inputs_changed_erased(&mut self, owner: ComponentInstanceId) -> bool;
    fn unmounted_erased(&mut self, owner: ComponentInstanceId);
}

impl<C: Component> ErasedComponent for C {
    fn component_type_id(&self) -> TypeId {
        TypeId::of::<C>()
    }

    fn component_type_name(&self) -> &'static str {
        std::any::type_name::<C>()
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }

    fn into_any(self: Box<Self>) -> Box<dyn Any> {
        self
    }

    fn update_from(&mut self, incoming: Box<dyn ErasedComponent>) -> Result<bool, ViewError> {
        let actual = incoming.component_type_name();
        let incoming =
            incoming
                .into_any()
                .downcast::<C>()
                .map_err(|_| ViewError::ComponentTypeMismatch {
                    expected: std::any::type_name::<C>(),
                    actual,
                })?;
        Ok(self.update_inputs(*incoming))
    }

    fn render(&self, owner: ComponentInstanceId, target: RuntimeTarget) -> RenderedView {
        let (element, signals) =
            crate::compose::context::evaluate::<C, _>(owner, target, || self.view().into_element());
        RenderedView { element, signals }
    }

    fn mounted_erased(&mut self, owner: ComponentInstanceId) -> bool {
        let mut context = MountContext::new(owner);
        self.mounted(&mut context);
        context.update_requested()
    }

    fn inputs_changed_erased(&mut self, owner: ComponentInstanceId) -> bool {
        let mut context = InputsChangedContext::new(owner);
        self.inputs_changed(&mut context);
        context.update_requested()
    }

    fn unmounted_erased(&mut self, owner: ComponentInstanceId) {
        self.unmounted(&mut UnmountContext::new(owner));
    }
}

#[doc(hidden)]
pub struct RenderedView {
    pub element: Element,
    pub signals: Vec<SignalDependency>,
}
