//! Curated values shared by the baseline application component catalog.

pub use crate::application_components::{
    ActionFactory, Activation, ActivityIndicator, ActivityIndicatorDensityStyle,
    ActivityIndicatorError, ActivityIndicatorRef, ActivityIndicatorState, ActivityIndicatorStyle,
    ActivityIndicatorStyleId, ActivityIndicatorVisualStyle, ActivityMotionPreference,
    ActivityMotionStyle, AdaptiveScaffold, AdaptiveScaffoldError, AdaptiveScaffoldPlan,
    AdaptiveScaffoldPolicy, AdaptiveScaffoldPolicyError, AdaptiveScaffoldRef,
    AdaptiveScaffoldStyle, AdaptiveScaffoldTransition, AdaptiveSlotPlan, AdaptiveSlotPresentation,
    AdaptiveSlotTransition, AdaptiveWidthClass, ApplicationOverlayCommand,
    ApplicationOverlayController, ApplicationOverlayControllerError,
    ApplicationOverlayControllerState, ApplicationOverlayEffect, ApplicationOverlayHost,
    ApplicationOverlayHostError, ApplicationOverlayHostRef, ApplicationPopupPlacement,
    ApplicationPopupPlacementError, ApplicationPopupPlacementPolicy,
    ApplicationPopupPlacementRequest, Breadcrumb, BreadcrumbError, BreadcrumbItem,
    BreadcrumbItemError, BreadcrumbItemRef, BreadcrumbRef, BreadcrumbSelectionRequest,
    BreadcrumbStyle, Button, ButtonBehavior, ButtonBusyPolicy, ButtonError, ButtonInteractionState,
    ButtonRef, ButtonStyle, ButtonStyleId, ButtonStyleState, ButtonVisualStyle, ChangePhase,
    ChangeSource, CheckCycleError, CheckCyclePolicy, CheckState, Checkbox, CheckboxError,
    CheckboxRef, CheckboxStateStyle, CheckboxStyle, CheckboxVisualStyle, CommandInvocation,
    CommandModelError, CommandOwnerField, CommandShortcut, CommandShortcutOutcome,
    CommandShortcutRegistration, CommandShortcutRegistrationError, CommandShortcutScope,
    CommandShortcutScopeError, CommandSpec, CompositionChanged, ContextMenu, ContextMenuDismissal,
    ContextMenuError, ContextMenuOpenRequest, ContextMenuOpened, ContextMenuOpening, DataGrid,
    DataGridActivation, DataGridCell, DataGridDiagnostics, DataGridError, DataGridNavigation,
    DataGridRef, DataGridStyle, DensityClass, DensityMetrics, Dialog, DialogBarrierIntent,
    DialogBarrierPolicy, DialogError, DialogInitialFocus, DialogKind, DialogOpened, EditHistory,
    EditHistoryAvailability, EditHistoryCommand, EditHistoryDiagnostics, EditHistoryError,
    EditHistoryKind, EditHistoryPolicy, EditHistoryPolicyError, EditHistoryRecordOutcome,
    EditRejected, EditRejectedReason, FieldMetadata, FieldMetadataError, FieldSemanticSupport,
    FieldValidation, Form, FormAcceptedSubmission, FormDiagnostics, FormError, FormFocusIntent,
    FormInvalidSubmission, FormRevealIntent, FormSubmission, FormUpdate, IconArtwork, IconButton,
    IconButtonError, IconButtonRef, IconButtonStyle, IconButtonVisualStyle, IconSlotStyle,
    IconSlotStyleError, ImageView, ImageViewContent, ImageViewError, ImageViewRef,
    ImageViewSemanticPolicy, ImageViewStyle, InteractiveTargetSize, Label, LabelContent,
    LabelError, LabelRef, LabelStyle, LabelTextStyle, LabelTextStyleError, Link, LinkAction,
    LinkCommand, LinkCommandKind, LinkDestination, LinkDestinationError, LinkError, LinkRef,
    LinkStyle, LinkVisualStyle, ListBox, ListBoxDiagnostics, ListBoxError, ListBoxItemsUpdate,
    ListBoxOption, ListBoxOptionError, ListBoxOptionRef, ListBoxRef, ListBoxSelectionRequest,
    ListBoxStyle, ListBoxTransition, ListView, ListViewDiagnostics, ListViewError, ListViewItem,
    ListViewItemError, ListViewMove, ListViewRef, ListViewRowRef, ListViewStyle, ListViewUpdate,
    Menu, MenuActivationDismissal, MenuButton, MenuButtonError, MenuButtonOpenRequest,
    MenuButtonRef, MenuCommandIntent, MenuController, MenuControllerError, MenuDispatch, MenuError,
    MenuInteractionError, MenuItem, MenuItemKind, MenuItemRef, MenuLevelState, MenuNavigation,
    MenuOpenRequest, MenuOpened, MenuOpeningFocus, MenuRef, MenuRouteRequest, MenuStyle,
    MenuSubmenuCancellation, MenuSubmenuDeadline, MenuSubmenuIntent, MenuTypeaheadIntent, Meter,
    MeterBand, MeterBands, MeterError, MeterLevel, MeterLevelColors, MeterRef, MeterStyle,
    MeterVisualStyle, NavigationBar, NavigationBarBehavior, NavigationBarDestination,
    NavigationBarDestinationError, NavigationBarDestinationRef, NavigationBarError,
    NavigationBarNavigation, NavigationBarNavigationKind, NavigationBarPolicy, NavigationBarRef,
    NavigationBarSelectionRequest, NavigationBarStyle, NavigationController, NavigationDiagnostics,
    NavigationEntry, NavigationError, NavigationRail, NavigationRailBehavior,
    NavigationRailDestination, NavigationRailDestinationError, NavigationRailDestinationRef,
    NavigationRailError, NavigationRailNavigation, NavigationRailNavigationKind,
    NavigationRailPolicy, NavigationRailRef, NavigationRailSelectionRequest, NavigationRailStyle,
    NavigationRestorationKey, NavigationSelectionRequest, NavigationTransition,
    NavigationTransitionKind, NumericCommit, NumericField, NumericFieldCommand,
    NumericFieldCommandAvailability, NumericFieldError, NumericFieldOutput, NumericFieldRef,
    NumericFieldScalar, NumericFieldState, NumericIntermediate, NumericInvalid,
    NumericScalarParseError, Popup, PopupAnchor, PopupError, PopupOpened, ProgressDensityStyle,
    ProgressError, ProgressIndicator, ProgressMode, ProgressRef, ProgressStyle, ProgressValue,
    ProgressVisualStyle, RadioGroup, RadioGroupBehavior, RadioGroupError, RadioGroupRef,
    RadioGroupTransition, RadioItem, RadioItemError, RadioItemRef, RadioItemStateStyle,
    RadioItemVisualStyle, RadioStyle, RangeAffix, RangeFormat, RangeMark, RangeModel,
    RangeModelError, RangeNumber, RangeScalar, ResolvedActivityIndicatorStyle, ResolvedButtonStyle,
    ResolvedCheckboxStyle, ResolvedCommandShortcut, ResolvedCommandState, ResolvedIconButtonStyle,
    ResolvedLinkStyle, ResolvedMeterStyle, ResolvedProgressStyle, ResolvedRadioItemStyle,
    ResolvedSheetEdge, ResolvedSliderStyle, ResolvedSwitchStyle, ResolvedToastCorner,
    ResolvedToastExtent, ResolvedToggleButtonStyle, RevealAlignment, RevealRequest,
    STANDARD_APPLICATION_POPUP_CANDIDATES, Scaffold, ScaffoldError, ScaffoldRef, ScaffoldSlot,
    ScaffoldSlotRef, ScaffoldSlotSpec, ScaffoldSlotSpecError, ScaffoldStyle, ScrollActivity,
    ScrollAnchorMode, ScrollBar, ScrollBarBehavior, ScrollBarCommand, ScrollBarError,
    ScrollBarModel, ScrollBarRef, ScrollBarStyle, ScrollBarThumbGeometry, ScrollBarTrackGeometry,
    ScrollCancelReason, ScrollChangeSource, ScrollController, ScrollControllerCommand,
    ScrollControllerError, ScrollControllerOutcome, ScrollDiagnostics, ScrollError,
    ScrollExtentAnchor, ScrollInputSource, ScrollMetrics, ScrollMotionId, ScrollMotionRequest,
    ScrollPhysics, ScrollState, ScrollUpdate, ScrollView, ScrollViewAxis, ScrollViewBehavior,
    ScrollViewCommand, ScrollViewError, ScrollViewRef, ScrollViewStyle, SearchField,
    SearchFieldCommand, SearchFieldCommandAvailability, SearchFieldError, SearchFieldOutput,
    SearchFieldRef, SecureContentExposure, SecureContextCapabilities,
    SecureContextCommandAvailability, SecureField, SecureFieldCommand,
    SecureFieldCommandAvailability, SecureFieldError, SecureFieldOutput, SecureFieldPrivacyPolicy,
    SecureFieldRef, SecureFieldUpdate, SelectableText, SelectableTextBehavior, SelectableTextError,
    SelectableTextRef, SelectionChanged, SelectionDiagnostics, SelectionError,
    SelectionFollowsFocus, SelectionItemsUpdate, SelectionMode, SelectionModel, SelectionProposal,
    SelectionProposalKind, SelectionTransition, Separator, SeparatorError, SeparatorGeometry,
    SeparatorOrientation, SeparatorRef, SeparatorSemanticPolicy, SeparatorStyle, Sheet,
    SheetBarrierIntent, SheetBarrierPolicy, SheetEdge, SheetError, SheetExtent, SheetInitialFocus,
    SheetMode, SheetOpened, ShortcutDisplayBinding, ShortcutDisplayBindingError, ShortcutSet,
    ShortcutSetError, Slider, SliderBehavior, SliderCommand, SliderError, SliderInteractionState,
    SliderOrientation, SliderPointerOutcome, SliderRef, SliderStyle, SliderStyleState,
    SliderTrackGeometry, SliderVisualStyle, Submitted, Switch, SwitchError, SwitchRef,
    SwitchStateStyle, SwitchStyle, SwitchVisualStyle, Tab, TabActivationPolicy, TabBehavior,
    TabError, TabNavigation, TabNavigationKind, TabOrientation, TabPanelRef, TabPolicy, TabRef,
    TabSelectionRequest, Table, TableCell, TableCellRef, TableColumn, TableColumnError,
    TableColumnRef, TableError, TableRef, TableRow, TableRowError, TableRowRef, TableStyle, Tabs,
    TabsError, TabsRef, TabsStyle, TargetAssessment, TextArea, TextAreaCommand, TextAreaError,
    TextAreaOutput, TextAreaRef, TextAreaReturnPolicy, TextChanged, TextController,
    TextControllerError, TextControllerHistoryError, TextControllerSessionOutcome,
    TextControllerUpdate, TextField, TextFieldCommand, TextFieldCommandAvailability,
    TextFieldError, TextFieldMode, TextFieldOutput, TextFieldRef, TextFieldStyle,
    TextFieldVisualStyle, Toast, ToastAnnouncementIntent, ToastAnnouncementPolicy,
    ToastAnnouncementPriority, ToastCoalescingIntent, ToastCoalescingKey, ToastCorner,
    ToastDeadlineError, ToastDismissalIntent, ToastDismissalPolicy, ToastError, ToastExpiryIntent,
    ToastExtent, ToastLifetime, ToastLifetimeError, ToastOpened, ToastRedactionIntent,
    ToggleButton, ToggleButtonError, ToggleButtonRef, ToggleButtonStyle, Toolbar, ToolbarBehavior,
    ToolbarCommandRequest, ToolbarError, ToolbarInvocation, ToolbarInvocationError, ToolbarItemRef,
    ToolbarNavigationPolicy, ToolbarOrientation, ToolbarRef, ToolbarStyle, ToolbarTransition,
    Tooltip, TooltipAccessibleContribution, TooltipAnchor, TooltipDeadlineError,
    TooltipDeadlineIntent, TooltipDismissalPolicy, TooltipError, TooltipExtent, TooltipOpened,
    TooltipSemanticsIntent, TooltipTrigger, TooltipTriggerPolicy, TooltipTriggerPolicyError,
    TreeExpansionProposal, TreeExpansionTransition, TreeGrid, TreeGridActivation,
    TreeGridDiagnostics, TreeGridError, TreeGridNavigation, TreeGridRef, TreeHierarchy,
    TreeHierarchyDiagnostics, TreeHierarchyError, TreeItem, TreeItemError, TreeItemRef, TreeView,
    TreeViewActivation, TreeViewDiagnostics, TreeViewError, TreeViewExpansionTransition,
    TreeViewNavigation, TreeViewRef, TreeViewStyle, ValidationKind, ValidationMessage,
    ValidationResult, ValidationResultError, ValidationSummary, ValidationSummaryAction,
    ValidationSummaryEntry, ValidationSummaryEntryRef, ValidationSummaryError,
    ValidationSummaryRef, ValidationSummaryStyle, ValueChange, VirtualListError, VirtualListPlan,
    VirtualListPolicy, VirtualListPolicyError, VirtualListRowRef, VirtualListStyle,
    VirtualListTotal, VirtualListUpdate, VirtualListView, VirtualListViewRef, VirtualListViewport,
    VirtualListViewportError, place_application_popup, standard_listbox_policy,
    standard_radio_policy,
};
