//! Curated shell-component authoring surface.

pub use crate::input::Activation;
pub use crate::runtime::MonotonicInstant;
pub use crate::shell::{
    ApplicationAction, ApplicationActionId, ApplicationActionKind, ApplicationDescription,
    ApplicationEntry, ApplicationIconId, ApplicationId, ApplicationLabel, ApplicationRevision,
    ApplicationStates, ClientSurfaceSnapshot, InputSource, NotificationAction,
    NotificationActionId, NotificationActionKind, NotificationDeliveryState, NotificationIconId,
    NotificationId, NotificationLifecycle, NotificationPersistence, NotificationPriority,
    NotificationPrivacy, NotificationRevision, NotificationSnapshot, NotificationText, OutputEdge,
    OutputId, OutputRequest, OutputRevision, ReservedAreaExtent, ReservedAreaId, ShellLayerKind,
    StatusAction, StatusActionId, StatusActionKind, StatusEntry, StatusEntryId, StatusEntryKind,
    StatusIconId, StatusPrivacy, StatusSeverity, StatusText, SurfaceId, SurfaceInputContact,
    SurfaceRequest, SurfaceRevision, SystemRequest, SystemStatusRevision, SystemStatusSnapshot,
    WorkspaceId, WorkspaceRequest, WorkspaceRevision, WorkspaceSnapshot, WorkspaceSurface,
};
pub use crate::shell_components::{
    ApplicationActionIntent, ApplicationActionSourceError, ApplicationCatalog,
    ApplicationCatalogError, ApplicationGrid, ApplicationGridError, ApplicationGridItemRef,
    ApplicationGridMountError, ApplicationGridRef, ApplicationGridStyle, ApplicationItemRef, Dock,
    DockError, DockMountError, DockRef, DockStyle, FloatingRegion, FloatingRegionError,
    FloatingRegionMountError, FloatingRegionRef, FloatingRegionStyle, Launcher, LauncherError,
    LauncherMountError, LauncherRef, LauncherStyle, LockComposition, LockCompositionError,
    LockCompositionMountError, LockCompositionRef, LockCompositionStyle, MediaStatus,
    MediaStatusError, MediaStatusRef, NotificationActionIntent, NotificationActionRef,
    NotificationActionSourceError, NotificationCatalog, NotificationCatalogError,
    NotificationCenter, NotificationCenterError, NotificationCenterMountError,
    NotificationCenterRef, NotificationCenterStyle, NotificationHost, NotificationHostError,
    NotificationHostMountError, NotificationHostRef, NotificationHostStyle, NotificationRef,
    OnScreenDisplay, OnScreenDisplayError, OnScreenDisplayMountError, OnScreenDisplayRef,
    OnScreenDisplayStyle, Panel, PanelAutoHideError, PanelAutoHideInput, PanelAutoHidePolicy,
    PanelAutoHideSnapshot, PanelAutoHideState, PanelAutoHideTransition, PanelError,
    PanelMountError, PanelRef, PanelRevealSource, PanelStyle, QuickSettings,
    QuickSettingsActionRef, QuickSettingsError, QuickSettingsMountError, QuickSettingsRef,
    QuickSettingsStyle, ShadowFrame, ShadowFrameError, ShadowFrameMountError, ShadowFrameRef,
    ShadowFrameStyle, ShellComponentDiagnosticCollector, ShellComponentDiagnosticKind,
    ShellComponentDiagnostics, SnapPreview, SnapPreviewError, SnapPreviewMountError,
    SnapPreviewRef, SnapPreviewStyle, StartMenu, StartMenuError, StartMenuMountError, StartMenuRef,
    StartMenuStyle, StatusActionIntent, StatusActionSourceError, StatusArea, StatusAreaEntryRef,
    StatusAreaError, StatusAreaMountError, StatusAreaRef, StatusAreaStyle, StatusClock,
    StatusClockError, StatusClockRef, StatusExtensionSlot, StatusExtensionSlotError,
    StatusExtensionSlotRef, StatusIndicator, StatusIndicatorError, StatusIndicatorRef,
    SystemDialog, SystemDialogActionRef, SystemDialogError, SystemDialogMountError,
    SystemDialogRef, SystemDialogStyle, SystemModalHost, SystemModalHostError,
    SystemModalHostMountError, SystemModalHostRef, SystemModalHostStyle, Taskbar, TaskbarError,
    TaskbarMountError, TaskbarRef, TaskbarStyle, TilingRegion, TilingRegionError,
    TilingRegionMountError, TilingRegionRef, TilingRegionStyle, TitleBarMoveError,
    TitleBarMoveIntent, TitlebarMoveError, TitlebarMoveIntent, WindowControl, WindowControlIntent,
    WindowControlRef, WindowControls, WindowControlsError, WindowControlsMountError,
    WindowControlsRef, WindowControlsStyle, WindowControlsStyleId, WindowFrame, WindowFrameError,
    WindowFrameMountError, WindowFrameRef, WindowFrameStyle, WindowStack, WindowStackEntry,
    WindowStackError, WindowStackHost, WindowStackMountError, WindowStackRef, WindowStackStyle,
    WindowTitleBar, WindowTitleBarError, WindowTitleBarMountError, WindowTitleBarRef,
    WindowTitleBarStyle, WindowTitlebar, WindowTitlebarError, WindowTitlebarMountError,
    WindowTitlebarRef, WindowTitlebarStyle, WorkspaceCatalog, WorkspaceCatalogError,
    WorkspaceOverview, WorkspaceOverviewError, WorkspaceOverviewItemRef,
    WorkspaceOverviewMountError, WorkspaceOverviewRef, WorkspaceOverviewStyle,
    WorkspaceOverviewSurfaceRef, WorkspaceSelectionIntent, WorkspaceSelectionSourceError,
    WorkspaceSwitcher, WorkspaceSwitcherError, WorkspaceSwitcherItemRef,
    WorkspaceSwitcherMountError, WorkspaceSwitcherRef, WorkspaceSwitcherStyle, WorkspaceView,
    WorkspaceViewError, WorkspaceViewMountError, WorkspaceViewRef, WorkspaceViewStyle,
    is_indicator_kind,
};
pub use crate::shell_primitives::{OutputViewRef, ShellLayerRef, ShellRootRef};
